'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LauncherV3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;body bgcolor=&quot;#000000&quot;&gt;
        '''&lt;center&gt;
        '''
        '''&lt;font size=&quot;-3&quot;&gt;
        '''&lt;pre&gt;&lt;font color=black&gt;omg-repz-and-aiw3-are-fucking-copycat-projects-.-omg-repz-and-aiw3-are&lt;/font&gt;&lt;br&gt;&lt;font color=black&gt;-fucking-copycat-projects-.-omg-repz-and-aiw3-are-fucking-copycat-proj&lt;/font&gt;&lt;br&gt;&lt;font color=black&gt;ects-.-omg-repz-and-aiw3-are-fucking-copycat-projects-.-omg-repz-an&lt;/font&gt;&lt;font color=#010101&gt;d-a&lt;/font&gt;&lt;br&gt;&lt;font color=black&gt;i&lt;/font&gt;&lt;font color=#040404&gt;w&lt;/font&gt;&lt;font color=#494949&gt;3&lt;/font&gt;&lt;font color=#a4a4a4&gt;-&lt;/font&gt;&lt;font color=#a5a5 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _error() As String
            Get
                Return ResourceManager.GetString("_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property updt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("updt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
